### ISSUE TITLE
.leave abc quit

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client-Bugs#109]
> This is an auto-generated error report for the [Wurst Client](https://www.wurst-client.tk).
Source: https://gist.github.com/anonymous/7185edf9fc07d45166c9119ac9c533f6

# Description
An error occurred in `.leave` while executing.
Exact input: `.leave iambernhard quit`

# Stacktrace
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at tk.wurst_client.mods.AutoLeaveMod.setMode(AutoLeaveMod.java:104)
	at tk.wurst_client.commands.LeaveCmd.execute(LeaveCmd.java:42)
	at tk.wurst_client.commands.CmdManager.onSentMessage(CmdManager.java:118)
	at net.minecraft.client.entity.EntityPlayerSP.sendChatMessage(EntityPlayerSP.java:334)
	at net.minecraft.client.gui.GuiScreen.func_175281_b(GuiScreen.java:487)
	at net.minecraft.client.gui.GuiScreen.func_175275_f(GuiScreen.java:477)
	at net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:132)
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:617)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:568)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1874)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1200)
	at net.minecraft.client.Minecraft.run(Minecraft.java:380)
	at net.minecraft.client.main.Main.main(Main.java:129)

```

# System details
- OS: Windows 10 (x86)
- Java version: 1.8.0_91 (Oracle Corporation)
- Wurst version: 2.21.2 (latest: 2.21.2)
- Timestamp: 2016.05.20-11:49:04

**Comment by mcccs** [comment]
I found that this is a duplicate : #10
