### ISSUE TITLE
Bugreporter doesn't work

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client-Bugs#11]
#### Description of the Bug
When the bug reporter opens, and if we click **View Bug**, this is what happens:
![screen shot 2016-05-02 at 16 30 29](https://cloud.githubusercontent.com/assets/11584045/14955525/368436ca-1083-11e6-820f-ef3d9bcf0f29.png)
If we click report bug, here's the bug-reporter-console-output:
```markdown
> This is an auto-generated error report for the [Wurst Client](https://www.wurst-client.tk).

# Description
�desc

# Stacktrace

�trace


# System details
- OS: �os
- Java version: �java
- Wurst version: �wurst
- Timestamp: �time

java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.github.com/gists
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at tk.wurst_client.utils.MiscUtils.post(MiscUtils.java:198)
	at tk.wurst_client.utils.MiscUtils.post(MiscUtils.java:173)
	at tk.wurst_client.gui.error.GuiError.actionPerformed(GuiError.java:106)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:490)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:595)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:564)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1833)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1154)
	at net.minecraft.client.Minecraft.run(Minecraft.java:455)
	at net.minecraft.client.main.Main.main(Main.java:115)
[16:32:08] [Client thread/INFO]: [CHAT] §c[§6Wurst§c]§f §c[§4§lERROR§c]§f Something went wrong with that error report.
```
#### How to Reproduce the Bug
I use `.leave mode tp` to open this window.

#### Other Information
- Wurst Client version: 3.0
- Operating system: Mac OS 10.11.4

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by ThisTestUser** [comment]
Are you running this via eclipse?

**Comment by mcccs** [comment]
https://github.com/Wurst-Imperium/Wurst-Client-for-MC-1.9.X/commit/ac32e3b71c1aa67d7cf4b9c7b6cce2411195b5fd
