### ISSUE TITLE
Killaura crash (NullPointer in EntityUtils) (MC 1.10)

### ISSUE THREAD

**Issue by TBB007** [Wurst-Imperium/Wurst-Client-Bugs#129]
When I'm on a server or in singleplayer and I activate MobESP with ChestESP, my game crash and I have to play with the normal minecraft 1.10.2 instead of the wurst client.

When I'm using ChestESP and then I activate MobESP the game crashes. (Theres not even alot of mobs or chests around) 

Wurst 1.10.X 

---

[crash-2016-07-18_22.33.33-client.txt](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/370569/crash-2016-07-18_22.33.33-client.txt)

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// There are four lights!

Time: 16-07-18 22:33
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
	at tk.wurst_client.utils.EntityUtils.isCorrectEntity(EntityUtils.java:135)
	at tk.wurst_client.utils.EntityUtils.getClosestEntity(EntityUtils.java:208)
	at tk.wurst_client.mods.KillauraMod.onUpdate(KillauraMod.java:90)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
	at net.minecraft.world.World.updateEntity(World.java:1940)
	at net.minecraft.world.World.updateEntities(World.java:1790)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:120)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at tk.wurst_client.utils.EntityUtils.isCorrectEntity(EntityUtils.java:135)
	at tk.wurst_client.utils.EntityUtils.getClosestEntity(EntityUtils.java:208)
	at tk.wurst_client.mods.KillauraMod.onUpdate(KillauraMod.java:90)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
	Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
	at net.minecraft.world.World.updateEntity(World.java:1940)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 179683
	Entity Name: TBB007
	Entity's Exact location: -33,23, 60,00, 12,31
	Entity's Block location: World: (-34,60,12), Chunk: (at 14,3,12 in -3,0; contains blocks -48,0,0 to -33,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0,04, 0,00, 0,01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1790)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TBB007'/179683, l='MpServer', x=-33,23, y=60,00, z=12,31]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-82,249,559), Chunk: (at 14,15,15 in -6,34; contains blocks -96,0,544 to -81,255,559), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 6151978 game time, 6151978 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 30 total; [EntityPlayerSP['TBB007'/179683, l='MpServer', x=-33,23, y=60,00, z=12,31], EntityEnderCrystal['entity.EnderCrystal.name'/179713, l='MpServer', x=12,50, y=95,00, z=39,50], EntityEnderman['Enderman'/179718, l='MpServer', x=6,63, y=59,00, z=-35,50], EntityEnderCrystal['entity.EnderCrystal.name'/179719, l='MpServer', x=12,50, y=80,00, z=-38,50], EntityEnderman['Enderman'/179720, l='MpServer', x=9,50, y=59,00, z=53,50], EntityEnderman['Enderman'/179686, l='MpServer', x=-36,48, y=60,00, z=0,41], EntityEnderman['Enderman'/179687, l='MpServer', x=-33,77, y=60,00, z=12,23], EntityEnderman['Enderman'/179684, l='MpServer', x=-33,03, y=60,00, z=13,01], EntityEnderman['Enderman'/179685, l='MpServer', x=-34,02, y=60,00, z=12,85], EntityEnderman['Enderman'/179690, l='MpServer', x=-44,22, y=61,00, z=-6,88], EntityEnderman['Enderman'/179691, l='MpServer', x=-31,46, y=60,00, z=10,46], EntityEnderCrystal['entity.EnderCrystal.name'/179688, l='MpServer', x=-41,50, y=98,00, z=0,50], EntityEnderman['Enderman'/179689, l='MpServer', x=-40,32, y=61,00, z=-4,50], EntityEnderman['Enderman'/179694, l='MpServer', x=-29,84, y=60,00, z=-4,60], EntityEnderman['Enderman'/179695, l='MpServer', x=-18,65, y=60,00, z=-7,48], EntityEnderCrystal['entity.EnderCrystal.name'/179692, l='MpServer', x=-32,50, y=92,00, z=24,50], EntityEnderman['Enderman'/179693, l='MpServer', x=-26,61, y=60,00, z=-4,50], EntityEnderCrystal['entity.EnderCrystal.name'/179698, l='MpServer', x=-32,50, y=89,00, z=-23,50], EntityEnderman['Enderman'/179696, l='MpServer', x=-24,30, y=60,00, z=-3,11], EntityEnderman['Enderman'/179697, l='MpServer', x=-29,44, y=60,00, z=-6,41], EntityEnderman['Enderman'/179702, l='MpServer', x=-5,50, y=60,00, z=31,50], EntityEnderman['Enderman'/179703, l='MpServer', x=-2,50, y=59,00, z=39,50], EntityEnderman['Enderman'/179700, l='MpServer', x=-1,50, y=60,00, z=31,50], EntityEnderman['Enderman'/179701, l='MpServer', x=-2,50, y=60,00, z=29,50], EntityEnderman['Enderman'/179704, l='MpServer', x=-2,50, y=59,00, z=45,50], EntityEnderCrystal['entity.EnderCrystal.name'/179705, l='MpServer', x=-11,50, y=104,00, z=39,50], EntityEnderman['Enderman'/179710, l='MpServer', x=5,58, y=61,00, z=-23,53], EntityEnderman['Enderman'/179711, l='MpServer', x=1,50, y=61,00, z=-26,50], EntityEnderman['Enderman'/179708, l='MpServer', x=-18,50, y=58,00, z=56,50], EntityEnderCrystal['entity.EnderCrystal.name'/179709, l='MpServer', x=-11,50, y=86,00, z=-38,50]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2929)
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:120)

-- System Details --
Details:
	Minecraft Version: 1.10
	Wurst Client Version: 4.0 (latest: 4.0)
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 129905864 bytes (123 MB) / 282214400 bytes (269 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.10.X Wurst Client
	LWJGL: 2.9.4
	OpenGL: GeForce GT 640/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
```

**Comment by HackerOnMineCraft** [comment]
I know how to fix this, just follow these steps:

1. Press Windows+R (it'll bring up the Run application)
![capture3](https://cloud.githubusercontent.com/assets/20606343/17080945/68df068a-5111-11e6-87bd-6b68b57c8590.PNG)

2. Type "%appdata%\.minecraft\wurst\modules.json" and click "OK" (or "Run" if it shows that)
![capture2](https://cloud.githubusercontent.com/assets/20606343/17080938/209561da-5111-11e6-92a3-e9e338cb13d0.PNG)
3. Open it with Notepad (If you want to make your life easier, I would suggest using the program Notepad++)
![capture4](https://cloud.githubusercontent.com/assets/20606343/17080996/61ccd852-5113-11e6-800f-82f8e63349fe.PNG)
4. Press Ctrl+F
![capture5](https://cloud.githubusercontent.com/assets/20606343/17081013/e3d4936c-5113-11e6-88b0-c6b5c59dbf55.PNG)
5. Type "true" and click "Find Next"
![capture6](https://cloud.githubusercontent.com/assets/20606343/17081017/fd48d074-5113-11e6-9599-c08976b2a695.PNG)
6. Every time it finds the word true, change it to false
![capture7](https://cloud.githubusercontent.com/assets/20606343/17081021/0af40c0c-5114-11e6-8779-f7bc1212f3e1.PNG)

Note: Sometimes it will direct you to the hack TrueSight, don't touch that.
![capture8](https://cloud.githubusercontent.com/assets/20606343/17081025/9c9aadc8-5114-11e6-9ce5-204415713292.PNG)

**Comment by TBB007** [comment]
Thanks man!
