### ISSUE TITLE
AntiSpam / GuiNewChat crash (ConcurrentModificationException) (MC 1.10)

### ISSUE THREAD

**Issue by Stego27** [Wurst-Imperium/Wurst-Client-Bugs#136]
**Issue:**
Wurst crashes randomly on multiplayer.
[crash-2016-07-20_20.37.42-client.txt](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/374530/crash-2016-07-20_20.37.42-client.txt)
[crash-2016-07-20_14.21.24-client.txt](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/374532/crash-2016-07-20_14.21.24-client.txt)
[crash-2016-07-17_00.08.26-client.txt](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/374531/crash-2016-07-17_00.08.26-client.txt)

**How to Reproduce:**
Play on a server for a while.

**Other Information:**
- Wurst Client version: **4.0**
- Operating system: **Windows 10 Pro**

*I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.* [**✓**]

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Oops.

Time: 7/20/16 8:37 PM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.text.TextComponentBase.getFormattedText(TextComponentBase.java:92)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:96)
	at net.minecraft.client.gui.GuiIngame.renderGameOverlay(GuiIngame.java:365)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1176)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1133)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:120)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at net.minecraft.util.text.TextComponentBase.getFormattedText(TextComponentBase.java:92)
	at net.minecraft.client.gui.GuiNewChat.drawChat(GuiNewChat.java:96)
	at net.minecraft.client.gui.GuiIngame.renderGameOverlay(GuiIngame.java:365)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Stego27'/1554232, l='MpServer', x=-123477.54, y=72.00, z=1145753.84]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (176,64,-148), Chunk: (at 0,4,12 in 11,-10; contains blocks 176,0,-160 to 191,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 97842 game time, 42760195 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntitySkeleton['Skeleton'/1599513, l='MpServer', x=-123514.50, y=64.00, z=1145772.50], EntityCreeper['Creeper'/1607636, l='MpServer', x=-123470.50, y=38.00, z=1145748.50], EntityPig['Pig'/1540935, l='MpServer', x=-123452.46, y=96.00, z=1145730.05], EntityCow['Cow'/1540943, l='MpServer', x=-123486.45, y=91.00, z=1145738.59], EntityPig['Pig'/1540942, l='MpServer', x=-123455.71, y=96.00, z=1145735.62], EntityPig['Pig'/1540941, l='MpServer', x=-123454.74, y=95.00, z=1145740.48], EntityCow['Cow'/1540940, l='MpServer', x=-123471.52, y=94.00, z=1145727.82], EntityCreeper['Creeper'/1540939, l='MpServer', x=-123463.64, y=47.00, z=1145736.86], EntityWitch['Witch'/1540938, l='MpServer', x=-123458.50, y=41.00, z=1145733.86], EntityCreeper['Creeper'/1540937, l='MpServer', x=-123465.86, y=35.00, z=1145734.59], EntityCow['Cow'/1539017, l='MpServer', x=-123457.24, y=96.00, z=1145719.82], EntityPig['Pig'/1539016, l='MpServer', x=-123455.54, y=96.00, z=1145716.73], EntityCow['Cow'/1540936, l='MpServer', x=-123455.15, y=96.00, z=1145730.59], EntitySkeleton['Skeleton'/1559351, l='MpServer', x=-123487.30, y=49.50, z=1145749.70], EntitySkeleton['Skeleton'/1559350, l='MpServer', x=-123487.30, y=49.50, z=1145749.70], EntityCreeper['Creeper'/1559349, l='MpServer', x=-123470.16, y=58.00, z=1145751.54], EntitySkeleton['Skeleton'/1559348, l='MpServer', x=-123487.30, y=49.50, z=1145749.70], EntitySkeleton['Skeleton'/1559347, l='MpServer', x=-123487.30, y=49.50, z=1145749.70], EntitySkeleton['Skeleton'/1559346, l='MpServer', x=-123487.30, y=49.50, z=1145749.30], EntitySkeleton['Skeleton'/1559345, l='MpServer', x=-123487.30, y=49.50, z=1145749.70], EntitySkeleton['Skeleton'/1559344, l='MpServer', x=-123487.30, y=49.50, z=1145749.70], EntityEnderman['Enderman'/1559357, l='MpServer', x=-123511.50, y=35.00, z=1145759.50], EntityCreeper['Creeper'/1559356, l='MpServer', x=-123512.35, y=46.00, z=1145751.55], EntitySkeleton['Skeleton'/1559355, l='MpServer', x=-123513.50, y=26.00, z=1145753.50], EntityZombie['Zombie'/1558330, l='MpServer', x=-123496.45, y=37.00, z=1145731.75], EntitySpider['Spider'/1559354, l='MpServer', x=-123457.51, y=60.00, z=1145752.97], EntityCreeper['Creeper'/1559353, l='MpServer', x=-123462.21, y=53.00, z=1145746.46], EntityBat['Bat'/1559352, l='MpServer', x=-123490.25, y=49.10, z=1145758.25], EntitySkeleton['Skeleton'/1559343, l='MpServer', x=-123487.30, y=49.50, z=1145749.70], EntitySkeleton['Skeleton'/1559342, l='MpServer', x=-123487.30, y=49.50, z=1145749.70], EntityPlayerSP['Stego27'/1554232, l='MpServer', x=-123477.54, y=72.00, z=1145753.84]]
	Retry entities: 0 total; []
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2929)
	at net.minecraft.client.Minecraft.run(Minecraft.java:432)
	at net.minecraft.client.main.Main.main(Main.java:120)

-- System Details --
Details:
	Minecraft Version: 1.10
	Wurst Client Version: 4.0 (latest: 4.0)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3648162928 bytes (3479 MB) / 4281597952 bytes (4083 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -Xms4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.10.X Wurst Client
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5450 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: sphax 1.10, sphax 1.10 (blocks), sphax 1.10 (items), sphax 1.10 (damaged items), sphaxsounds (incompatible), sphaxmusic (incompatible)
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E8200 @ 2.66GHz
```

**Comment by Alexander01998** [comment]
Probably caused by AntiSpam.

**Comment by Stego27** [comment]
I've disabled antispam so ill see if it crashes again

**Comment by HackerOnMineCraft** [comment]
I've been having the same problem but with SpeedNuker
