### ISSUE TITLE
Smash Nuker Bug

### ISSUE THREAD

**Issue by PigglesPorkchops** [Wurst-Imperium/Wurst-Client-Bugs#192]
#### Description of the Bug
When Smash Nuker is used in 1.10 WURST client it crashes.

#### How to Reproduce the Bug
Open up 1.10 WURST, go to a world and enable it.
After crashing first time when enter again you crash.

Note:
Also I looked at other posts but thing is with the latest version of WURST you don't get a folder named WURST, but one named 1.10.X Wurst Client inside the ZIP file, and inside that there is no modules folder. It used to work untill bug happened
#### Other Information
- Wurst Client version: 
- Operating system: 

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

Completely ignored arguments: [--nativeLauncherVersion, 307]
[10:38:05] [Client thread/INFO]: Setting user: AmberMage
[10:38:08] [Client thread/WARN]: Skipping bad option: lastServer:
[10:38:08] [Client thread/INFO]: LWJGL Version: 2.9.4
[10:38:09] [Client thread/INFO]: Reloading ResourceManager: Default
[10:38:13] [Sound Library Loader/INFO]: Starting up SoundSystem...
[10:38:13] [Thread-7/INFO]: Initializing LWJGL OpenAL
[10:38:13] [Thread-7/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[10:38:13] [Thread-7/INFO]: OpenAL initialized.
[10:38:13] [Sound Library Loader/INFO]: Sound engine started
[10:38:16] [Client thread/INFO]: Created: 1024x512 textures-atlas
[10:38:20] [Client thread/INFO]: No update found.
[10:38:40] [Server thread/INFO]: Starting integrated minecraft server version 1.10
[10:38:40] [Server thread/INFO]: Generating keypair
[10:38:41] [Server thread/INFO]: Preparing start region for level 0
[10:38:42] [Server thread/INFO]: Preparing spawn area: 23%
[10:38:43] [Server thread/INFO]: Changing view distance to 12, from 10
[10:38:44] [Server thread/INFO]: AmberMage[local:E:e9354e83] logged in with entity id 119 at (662.4155640603576, 4.0, 933.1632319195008)
[10:38:44] [Server thread/INFO]: AmberMage joined the game
[10:38:45] [Server thread/INFO]: Saving and pausing game...
[10:38:45] [Server thread/INFO]: Saving chunks for level 'WURST Settings'/Overworld
[10:38:45] [Server thread/INFO]: Saving chunks for level 'WURST Settings'/Nether
[10:38:45] [Server thread/INFO]: Saving chunks for level 'WURST Settings'/The End
java.lang.NullPointerException
	at net.minecraft.world.World.func_189509_E(World.java:257)
	at net.minecraft.world.World.getBlockState(World.java:872)
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:277)
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:119)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
	at net.minecraft.world.World.updateEntity(World.java:1940)
	at net.minecraft.world.World.updateEntities(World.java:1790)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:120)
[10:38:48] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Firing Wurst event
	at net.minecraft.world.World.updateEntities(World.java:1797) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:403) [1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:120) [1.10.X%20Wurst%20Client.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.func_189509_E(World.java:257) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.world.World.getBlockState(World.java:872) ~[1.10.X%20Wurst%20Client.jar:?]
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:277) ~[1.10.X%20Wurst%20Client.jar:?]
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:119) ~[1.10.X%20Wurst%20Client.jar:?]
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22) ~[1.10.X%20Wurst%20Client.jar:?]
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.world.World.updateEntity(World.java:1940) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.world.World.updateEntities(World.java:1790) ~[1.10.X%20Wurst%20Client.jar:?]
	... 4 more
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/16/16 10:38 AM
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
	at net.minecraft.world.World.func_189509_E(World.java:257)
	at net.minecraft.world.World.getBlockState(World.java:872)
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:277)
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:119)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
	at net.minecraft.world.World.updateEntity(World.java:1940)
	at net.minecraft.world.World.updateEntities(World.java:1790)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:120)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.func_189509_E(World.java:257)
	at net.minecraft.world.World.getBlockState(World.java:872)
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:277)
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:119)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
	Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
	at net.minecraft.world.World.updateEntity(World.java:1940)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 119
	Entity Name: AmberMage
	Entity's Exact location: 662.42, 4.00, 933.16
	Entity's Block location: World: (662,4,933), Chunk: (at 6,0,5 in 41,58; contains blocks 656,0,928 to 671,255,943), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1790)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['AmberMage'/119, l='MpServer', x=662.42, y=4.00, z=933.16]]
	Chunk stats: MultiplayerChunkCache: 573, 573
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (656,4,911), Chunk: (at 0,0,15 in 41,56; contains blocks 656,0,896 to 671,255,911), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 1725 game time, 1725 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 55 total; [EntitySlime['Slime'/8, l='MpServer', x=582.58, y=4.00, z=904.96], EntitySheep['Sheep'/9, l='MpServer', x=606.60, y=4.00, z=906.53], EntitySheep['Sheep'/10, l='MpServer', x=607.50, y=4.00, z=907.50], EntitySheep['Sheep'/11, l='MpServer', x=607.18, y=4.00, z=908.57], EntitySlime['Slime'/12, l='MpServer', x=602.46, y=4.33, z=903.90], EntitySlime['Slime'/13, l='MpServer', x=606.67, y=4.00, z=902.43], EntitySheep['Sheep'/14, l='MpServer', x=601.73, y=4.00, z=913.27], EntitySlime['Slime'/15, l='MpServer', x=594.90, y=4.00, z=938.20], EntityCow['Cow'/16, l='MpServer', x=598.54, y=4.00, z=957.60], EntityCow['Cow'/17, l='MpServer', x=601.44, y=4.00, z=946.83], EntityPig['Pig'/18, l='MpServer', x=592.43, y=4.00, z=952.48], EntityPig['Pig'/19, l='MpServer', x=600.08, y=4.00, z=946.14], EntitySlime['Slime'/20, l='MpServer', x=593.75, y=4.00, z=953.15], EntitySlime['Slime'/21, l='MpServer', x=605.15, y=4.00, z=973.56], EntitySlime['Slime'/22, l='MpServer', x=626.34, y=4.00, z=905.55], EntityCow['Cow'/23, l='MpServer', x=612.70, y=4.00, z=937.35], EntityCow['Cow'/24, l='MpServer', x=613.72, y=4.00, z=940.81], EntitySheep['Sheep'/25, l='MpServer', x=612.50, y=4.00, z=933.50], EntityCow['Cow'/26, l='MpServer', x=613.31, y=4.00, z=944.16], EntitySlime['Slime'/27, l='MpServer', x=610.70, y=4.00, z=945.45], EntitySlime['Slime'/28, l='MpServer', x=613.22, y=4.00, z=956.28], EntitySlime['Slime'/29, l='MpServer', x=607.10, y=4.00, z=973.74], EntitySlime['Slime'/30, l='MpServer', x=613.31, y=4.00, z=963.05], EntitySlime['Slime'/31, l='MpServer', x=616.16, y=4.00, z=976.80], EntitySlime['Slime'/32, l='MpServer', x=612.86, y=4.42, z=975.11], EntitySlime['Slime'/35, l='MpServer', x=633.50, y=4.00, z=891.97], EntityCow['Cow'/36, l='MpServer', x=638.79, y=4.00, z=983.80], EntityCow['Cow'/37, l='MpServer', x=636.50, y=4.00, z=988.50], EntitySlime['Slime'/38, l='MpServer', x=626.23, y=4.00, z=981.51], EntityCow['Cow'/39, l='MpServer', x=633.50, y=4.00, z=993.50], EntityPlayerSP['AmberMage'/119, l='MpServer', x=662.42, y=4.00, z=933.16], EntityCow['Cow'/40, l='MpServer', x=632.50, y=4.00, z=999.50], EntityPig['Pig'/49, l='MpServer', x=642.11, y=4.00, z=956.64], EntityPig['Pig'/50, l='MpServer', x=642.50, y=4.00, z=960.50], EntityPig['Pig'/51, l='MpServer', x=640.50, y=4.00, z=962.50], EntityPig['Pig'/52, l='MpServer', x=643.25, y=4.00, z=968.33], EntitySlime['Slime'/57, l='MpServer', x=658.80, y=4.00, z=878.96], EntitySlime['Slime'/58, l='MpServer', x=667.93, y=4.00, z=965.31], EntitySlime['Slime'/65, l='MpServer', x=680.19, y=4.00, z=939.07], EntitySlime['Slime'/66, l='MpServer', x=671.86, y=4.08, z=938.05], EntitySlime['Slime'/67, l='MpServer', x=683.63, y=4.00, z=968.67], EntitySlime['Slime'/68, l='MpServer', x=687.58, y=4.00, z=918.83], EntityCow['Cow'/69, l='MpServer', x=696.65, y=4.00, z=943.19], EntityCow['Cow'/70, l='MpServer', x=700.50, y=4.00, z=937.50], EntityCow['Cow'/71, l='MpServer', x=699.50, y=4.00, z=932.50], EntityPig['Pig'/72, l='MpServer', x=699.50, y=4.00, z=945.50], EntitySlime['Slime'/73, l='MpServer', x=690.13, y=4.42, z=1005.19], EntitySlime['Slime'/74, l='MpServer', x=692.71, y=4.00, z=991.89], EntitySlime['Slime'/77, l='MpServer', x=708.63, y=4.33, z=922.24], EntitySlime['Slime'/78, l='MpServer', x=718.38, y=4.00, z=945.98], EntitySlime['Slime'/81, l='MpServer', x=726.48, y=4.00, z=987.29], EntitySlime['Slime'/82, l='MpServer', x=722.44, y=4.25, z=982.26], EntitySlime['Slime'/83, l='MpServer', x=719.57, y=4.00, z=996.91], EntitySlime['Slime'/87, l='MpServer', x=741.83, y=4.14, z=902.01], EntitySlime['Slime'/88, l='MpServer', x=737.25, y=4.00, z=931.12]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2929)
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:120)

-- System Details --
Details:
	Minecraft Version: 1.10
	Wurst Client Version: 4.0 (latest: 4.0)
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 89724016 bytes (85 MB) / 303702016 bytes (289 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.10.X Wurst Client
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3304, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz
[10:38:49] [Server thread/INFO]: Stopping server
[10:38:49] [Server thread/INFO]: Saving players
[10:38:49] [Server thread/INFO]: Saving worlds
[10:38:49] [Server thread/INFO]: Saving chunks for level 'WURST Settings'/Overworld
[10:38:49] [Server thread/INFO]: Saving chunks for level 'WURST Settings'/Nether
[10:38:49] [Server thread/INFO]: Saving chunks for level 'WURST Settings'/The End
#@!@# Game crashed! Crash report saved to: C:\Users\rodney\AppData\Roaming\.minecraft\instances\Wurst\crash-reports\crash-2016-08-16_10.38.48-client.txt
#@!@# Please report this crash at: https://www.wurst-client.tk/bugs/

.

**Comment by qwestfrost** [comment]
I've found a way to fix this.
Since WURST 1.10 doesn't include the wurst folder, it's now stored in .minecraft\instances. Start menu > Search for %appdata% > Press enter > Go to .minecraft > open the "instances" folder > open the Wurst folder > Open the wurst (lowercase 'w') folder > open modules.json > CTRL + F search below "Nuker" and then change "enabled" from "true" to "false". Also turn off LegitNuker if it's enabled.

Boom, fixed.
