### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by tanmar123** [Wurst-Imperium/Wurst-Client-Bugs#197]
#### How to Reproduce the Bug
It started when i did nuker on mineplex, then i couldent join the server due to the bug, i could go on anything else,nthen later my screen went black, and i could do anything except servers and worlds
#### Other Information
- Wurst Client version: 1.10
- Operating system: Windows 7

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

```
----Crash Report----

---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// There are four lights!

Time: 19/08/16 11:10
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
	at net.minecraft.world.World.func_189509_E(World.java:257)
	at net.minecraft.world.World.getBlockState(World.java:872)
	at tk.wurst_client.mods.NukerLegitMod.find(NukerLegitMod.java:263)
	at tk.wurst_client.mods.NukerLegitMod.onUpdate(NukerLegitMod.java:137)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
	at net.minecraft.world.World.updateEntity(World.java:1940)
	at net.minecraft.world.World.updateEntities(World.java:1790)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:120)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.func_189509_E(World.java:257)
	at net.minecraft.world.World.getBlockState(World.java:872)
	at tk.wurst_client.mods.NukerLegitMod.find(NukerLegitMod.java:263)
	at tk.wurst_client.mods.NukerLegitMod.onUpdate(NukerLegitMod.java:137)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
	Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
	at net.minecraft.world.World.updateEntity(World.java:1940)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 1633205
	Entity Name: tanmar123
	Entity's Exact location: 12282.80, 130.00, 18295.73
	Entity's Block location: World: (12282,130,18295), Chunk: (at 10,8,7 in 767,1143; contains blocks 12272,0,18288 to 12287,255,18303), Region: (23,35; contains chunks 736,1120 to 767,1151, blocks 11776,0,17920 to 12287,255,18431)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1790)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['tanmar123'/1633205, l='MpServer', x=12282.80, y=130.00, z=18295.73]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (182,4,107), Chunk: (at 6,0,11 in 11,6; contains blocks 176,0,96 to 191,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 15171 game time, 155675 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['tanmar123'/1633205, l='MpServer', x=12282.80, y=130.00, z=18295.73]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.9-SNAPSHOT:438f7a9:unknown) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2929)
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:120)

-- System Details --
Details:
	Minecraft Version: 1.10
	Wurst Client Version: 4.0 (latest: 4.0)
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 137256392 bytes (130 MB) / 306978816 bytes (292 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.10.X Wurst Client
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 2.1.0 - Build 8.15.10.2281, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because EXT_framebuffer_object is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU M 380 @ 2.53GHz
```

**Comment by bobsourus** [comment]
this is happening to me as well

**Comment by tanmar123** [comment]
completely redownload wurst. thats what i did and it works very well

**Comment by tanmar123** [comment]
reinstall too
