### ISSUE TITLE
Nuker Crash - Collective Issue

### ISSUE THREAD

**Issue by GheJ** [Wurst-Imperium/Wurst-Client-Bugs#221]
**_When I try to go on a server  minecraft crash And I must close it from Task Manager and the text below is the crash report please help me_**

```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// This doesn't make any sense!

Time: 13/9/2016 11:31 πμ
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
    at net.minecraft.world.World.func_189509_E(World.java:257)
    at net.minecraft.world.World.getBlockState(World.java:872)
    at tk.wurst_client.mods.NukerMod.find(NukerMod.java:277)
    at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:119)
    at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
    at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
    at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
    at net.minecraft.world.World.updateEntity(World.java:1940)
    at net.minecraft.world.World.updateEntities(World.java:1790)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113)
    at net.minecraft.client.Minecraft.run(Minecraft.java:403)
    at net.minecraft.client.main.Main.main(Main.java:120)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.world.World.func_189509_E(World.java:257)
    at net.minecraft.world.World.getBlockState(World.java:872)
    at tk.wurst_client.mods.NukerMod.find(NukerMod.java:277)
    at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:119)
    at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
    Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
    at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
    at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
    at net.minecraft.world.World.updateEntity(World.java:1940)

-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
    Entity ID: 255012
    Entity Name: Ghex
    Entity's Exact location: 8,50, 65,00, -8,50
    Entity's Block location: World: (8,65,-9), Chunk: (at 8,4,7 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Entity's Momentum: 0,00, 0,00, 0,00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.updateEntities(World.java:1790)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Ghex'/255012, l='MpServer', x=8,50, y=65,00, z=-8,50]]
    Chunk stats: MultiplayerChunkCache: 9, 9
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,65,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 34358041 game time, 34360555 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityPlayerSP['Ghex'/255012, l='MpServer', x=8,50, y=65,00, z=-8,50]]
    Retry entities: 0 total; []
    Server brand: Waterfall (git:Waterfall-Bootstrap:1.10-SNAPSHOT:ea90d9e:57) <- PaperSpigot
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
    at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2929)
    at net.minecraft.client.Minecraft.run(Minecraft.java:424)
    at net.minecraft.client.main.Main.main(Main.java:120)

-- System Details --
Details:
    Minecraft Version: 1.10
    Wurst Client Version: 4.0 (latest: unknown)
    Operating System: Windows 10 (x86) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 133846168 bytes (127 MB) / 258478080 bytes (246 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    Launched Version: 1.10.X Wurst Client
    LWJGL: 2.9.4
    OpenGL: AMD Radeon HD 7500M/7600M Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Very likely; Jar signature invalidated
    Type: Client (map_client.txt)
    Resource Packs: ocdpack187113693.zip (incompatible)
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 4x Intel(R) Core(TM) i3-2328M CPU @ 2.20GHz
```

**Comment by Alexander01998** [comment]
This is a known bug that we have never managed to reproduce so far. It is caused by Nuker, but only happens if some special (currently unknown) condition is met.

Please answer the following questions:

1. Are there any special blocks or entities around you when this happens?
2. What server are you playing on when this happens?
3. Are you near the bottom or the top of the world when this happens?
4. Are you near the world border?

**Comment by RektBySkillz** [comment]
How do we fix this? Because wurst is the best i hack i know. But it wont work anymore because when i try to join  a single world my screen turns black. And because wurst saves the hacks you used. so reoinstalling it or restart youre game wont work :/

**Comment by Alexander01998** [comment]
Moved to #291.
