### ISSUE TITLE
Crash in Wurst Ver 2.22

### ISSUE THREAD

**Issue by YTJakeCrafter** [Wurst-Imperium/Wurst-Client-Bugs#240]
#### Description of the Bug

The game crash when I enter a world or a multiplayer server in ver 2.22. At first, I thought it wasn't successfully update using the auto update of Wurst. But after I customlly download it, it was the same result: crash
#### This is the Crash Report

---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// I blame Apple.

Time: 10/9/16 7:08 AM
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
    at net.minecraft.entity.Entity.getDistanceToEntity(Entity.java:1351)
    at tk.wurst_client.mods.KillauraLegitMod.onUpdate(KillauraLegitMod.java:56)
    at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
    at tk.wurst_client.events.EventManager.fire(EventManager.java:45)
    at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:132)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1884)
    at net.minecraft.world.World.updateEntity(World.java:1853)
    at net.minecraft.world.World.updateEntities(World.java:1702)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:2297)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1192)
    at net.minecraft.client.Minecraft.run(Minecraft.java:372)
    at net.minecraft.client.main.Main.main(Main.java:129)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.Entity.getDistanceToEntity(Entity.java:1351)
    at tk.wurst_client.mods.KillauraLegitMod.onUpdate(KillauraLegitMod.java:56)
    at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
    Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
    at tk.wurst_client.events.EventManager.fire(EventManager.java:45)
    at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:132)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1884)
    at net.minecraft.world.World.updateEntity(World.java:1853)

-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
    Entity ID: 6683
    Entity Name: kianyau
    Entity's Exact location: 0.50, 65.00, 0.50
    Entity's Block location: 0.00,65.00,0.00 - World: (0,65,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Rider: ~~ERROR~~ NullPointerException: null
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.updateEntities(World.java:1702)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['kianyau'/6683, l='MpServer', x=0.50, y=65.00, z=0.50]]
    Chunk stats: MultiplayerChunkCache: 350, 350
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 0.00,65.00,0.00 - World: (0,65,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 296003976 game time, 54000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
    Forced entities: 6 total; [EntityPlayerSP['kianyau'/6683, l='MpServer', x=0.50, y=65.00, z=0.50], EntityArmorStand['§7Welcome to §2§lMc§6§lGamer§b.§c§lZone'/6, l='MpServer', x=0.50, y=65.00, z=4.50], EntityArmorStand['§7Please §clogin§7 or §cregister§7 with'/7, l='MpServer', x=0.50, y=64.75, z=4.50], EntityArmorStand['§a/login§7 or §b/register'/8, l='MpServer', x=0.50, y=64.50, z=4.50], EntityArmorStand['§7--------------------------'/9, l='MpServer', x=0.50, y=64.25, z=4.50], EntityArmorStand['§bEnjoy your stay!'/10, l='MpServer', x=0.50, y=64.00, z=4.50]]
    Retry entities: 0 total; []
    Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.9-SNAPSHOT:4c7c64c:1151) <- Spigot
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:399)
    at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2834)
    at net.minecraft.client.Minecraft.run(Minecraft.java:394)
    at net.minecraft.client.main.Main.main(Main.java:129)

-- System Details --
Details:
    Minecraft Version: 1.8
    Wurst Client Version: 2.22 (latest: 2.22)
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 137905808 bytes (131 MB) / 300605440 bytes (286 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    Launched Version: Wurst
    LWJGL: 2.9.1
    OpenGL: GeForce 410M/PCI/SSE2 GL version 4.1.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: [-ºf-ºl32x InFinite.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
```
#### Contact me for further information

-Twitter: @YTJakeCrafter https://twitter.com/YTJakeCrafter
-Email: kianyau2003@gmail.com
#### Other Information
- Wurst Client version: Ver 2.22
- Operating system: Windows 7
---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by JDDanger101** [comment]
That happened to me to MacBookPro
