### ISSUE TITLE
Crashes On Join | Bug

### ISSUE THREAD

**Issue by FalloutGN** [Wurst-Imperium/Wurst-Client-Bugs#254]
#### Description of the Bug
What did you expect to happen?:
         Me to join the server and be able to join the server
and play as I have done, many, many, times.

What happened instead?

#### How to Reproduce the Bug
What does one need to do in order for this bug to occur?
Use the NEWEST verions of wurst and join play.cubecraft.net
Wait for it to say Log In
After that; it goes to the normal minecraft background screen (the dirt) stays like that for a few seconds
Then it crashes

#### Other Information
- Wurst 4.4; the Latest version
- Operating system: 
Windows 10

I couldn't find a answer on any other reports of THIS SAME EXACT BUG.
[crash-2016-09-12_13.56.33-client.txt](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/579994/crash-2016-09-12_13.56.33-client.txt)

[Log]
   Completely ignored arguments: [--nativeLauncherVersion, 307]
[23:09:42] [Client thread/INFO]: Setting user: CLASSIFIED
[23:09:44] [Client thread/INFO]: LWJGL Version: 2.9.4
[23:09:45] [Client thread/INFO]: Reloading ResourceManager: Default
[23:09:46] [Sound Library Loader/INFO]: Starting up SoundSystem...
[23:09:47] [Thread-7/INFO]: Initializing LWJGL OpenAL
[23:09:47] [Thread-7/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[23:09:47] [Thread-7/INFO]: OpenAL initialized.
[23:09:47] [Sound Library Loader/INFO]: Sound engine started
[23:09:48] [Client thread/INFO]: Created: 1024x512 textures-atlas
[23:09:55] [Client thread/INFO]: No update found.
[23:09:59] [Client thread/INFO]: Connecting to CLASSIFIED
[23:10:01] [Client thread/INFO]: [CHAT]                                      
java.lang.NullPointerException
	at net.minecraft.world.World.func_189509_E(World.java:254)
	at net.minecraft.world.World.getBlockState(World.java:869)
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:280)
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:120)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:222)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1987)
	at net.minecraft.world.World.updateEntity(World.java:1957)
	at net.minecraft.world.World.updateEntities(World.java:1807)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:120)
[23:10:02] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Firing Wurst event
	at net.minecraft.world.World.updateEntities(World.java:1814) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:403) [1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:120) [1.10.X%20Wurst%20Client.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.func_189509_E(World.java:254) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.world.World.getBlockState(World.java:869) ~[1.10.X%20Wurst%20Client.jar:?]
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:280) ~[1.10.X%20Wurst%20Client.jar:?]
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:120) ~[1.10.X%20Wurst%20Client.jar:?]
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22) ~[1.10.X%20Wurst%20Client.jar:?]
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:222) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1987) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.world.World.updateEntity(World.java:1957) ~[1.10.X%20Wurst%20Client.jar:?]
	at net.minecraft.world.World.updateEntities(World.java:1807) ~[1.10.X%20Wurst%20Client.jar:?]
	... 4 more
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Oops.

Time: 11/8/16 11:10 PM
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
	at net.minecraft.world.World.func_189509_E(World.java:254)
	at net.minecraft.world.World.getBlockState(World.java:869)
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:280)
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:120)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:222)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1987)
	at net.minecraft.world.World.updateEntity(World.java:1957)
	at net.minecraft.world.World.updateEntities(World.java:1807)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:120)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.func_189509_E(World.java:254)
	at net.minecraft.world.World.getBlockState(World.java:869)
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:280)
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:120)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
	Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:222)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1987)
	at net.minecraft.world.World.updateEntity(World.java:1957)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 12398
	Entity Name: AwesomeDev
	Entity's Exact location: 2000.52, 46.20, -4.51
	Entity's Block location: World: (2000,46,-5), Chunk: (at 0,2,11 in 125,-1; contains blocks 2000,0,-16 to 2015,255,-1), Region: (3,-1; contains chunks 96,-32 to 127,-1, blocks 1536,0,-512 to 2047,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1807)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['AwesomeDev'/12398, l='MpServer', x=2000.52, y=46.20, z=-4.51]]
	Chunk stats: MultiplayerChunkCache: 61, 61
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-999999,575,-999999), Chunk: (at 1,35,1 in -62500,-62500; contains blocks -1000000,0,-1000000 to -999985,255,-999985), Region: (-1954,-1954; contains chunks -62528,-62528 to -62497,-62497, blocks -1000448,0,-1000448 to -999937,255,-999937)
	Level time: 1031308886 game time, 5214796000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['AwesomeDev'/12398, l='MpServer', x=2000.52, y=46.20, z=-4.51]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCraft-Bootstrap:1.9.0-SNAPSHOT:7d281bd:unknown) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2929)
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:120)

-- System Details --
Details:
	Minecraft Version: 1.10
	Wurst Client Version: 4.4 (latest: 4.4)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 183924656 bytes (175 MB) / 287526912 bytes (274 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.10.X Wurst Client
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7560D GL version 4.5.13399 Compatibility Profile Context 15.200.1060.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-5500 APU with Radeon(tm) HD Graphics 
```
#@!@# Game crashed! Crash report saved to: CLASSIFIED\AppData\Roaming\.minecraft\crash-reports\crash-2016-11-08_23.10.02-client.txt
#@!@# Please report this crash at: https://www.wurst-client.tk/bugs/
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[Log]

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by Alexander01998** [comment]
Please answer my questions in https://github.com/Wurst-Imperium/Wurst-Client-Bugs/issues/221#issuecomment-246728704.
