### ISSUE TITLE
Crash on wordload

### ISSUE THREAD

**Issue by xApollo** [Wurst-Imperium/Wurst-Client-Bugs#265]
#### Description of the Bug
I expected to start a world/join a server without crashing.
Crashes on any world join even After Reinstalling.

#### How to Reproduce the Bug
I dont know. Load a world with wurst

#### Other Information
2.22
Win 7 

---

---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Ouch. That hurt :(

Time: 21.11.16 16:05
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
	at net.minecraft.entity.Entity.getDistanceToEntity(Entity.java:1351)
	at tk.wurst_client.mods.KillauraLegitMod.onUpdate(KillauraLegitMod.java:56)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:45)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:132)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1884)
	at net.minecraft.world.World.updateEntity(World.java:1853)
	at net.minecraft.world.World.updateEntities(World.java:1702)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2297)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1192)
	at net.minecraft.client.Minecraft.run(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(Main.java:129)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.Entity.getDistanceToEntity(Entity.java:1351)
	at tk.wurst_client.mods.KillauraLegitMod.onUpdate(KillauraLegitMod.java:56)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
	Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
	at tk.wurst_client.events.EventManager.fire(EventManager.java:45)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:132)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1884)
	at net.minecraft.world.World.updateEntity(World.java:1853)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 39359
	Entity Name: TheBigThank
	Entity's Exact location: -124,14, 74,89, -1600,32
	Entity's Block location: -125,00,74,00,-1601,00 - World: (-125,74,-1601), Chunk: (at 3,4,15 in -8,-101; contains blocks -128,0,-1616 to -113,255,-1601), Region: (-1,-4; contains chunks -32,-128 to -1,-97, blocks -512,0,-2048 to -1,255,-1537)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1702)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TheBigThank'/39359, l='MpServer', x=-124,14, y=74,89, z=-1600,32]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -116,00,4,00,-1591,00 - World: (-116,4,-1591), Chunk: (at 12,0,9 in -8,-100; contains blocks -128,0,-1600 to -113,255,-1585), Region: (-1,-4; contains chunks -32,-128 to -1,-97, blocks -512,0,-2048 to -1,255,-1537)
	Level time: 124 game time, 124 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['TheBigThank'/39359, l='MpServer', x=-124,14, y=74,89, z=-1600,32]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:399)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2834)
	at net.minecraft.client.Minecraft.run(Minecraft.java:394)
	at net.minecraft.client.main.Main.main(Main.java:129)

-- System Details --
Details:
	Minecraft Version: 1.8
	Wurst Client Version: 2.22 (latest: 2.22)
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 160071224 bytes (152 MB) / 429420544 bytes (409 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.5.0 NVIDIA 365.19, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by AAgamesnl** [comment]
just go to : %apdata%\.minecraft\wurst   and delete everything

**Comment by xApollo** [comment]
I said i reinstalled it and thats literally what i did and it still crashed 
It worked before part 2.22 tho

**Comment by AAgamesnl** [comment]
dude the %apdata%.minecraft\wurst folder is not the client folder


the %apdata%.minecraft\wurst folder is only a data folder

**Comment by xApollo** [comment]
no you dont say

**Comment by AAgamesnl** [comment]
Pls dude.  That folder Will stay there forever if you do anything on it.   Just delete that folder and open the latest wurst client 



Your data will be reset.    

Good luck
