### ISSUE TITLE
Wurst-Bot cannot connect to any server on wurst 4.6

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client-Bugs#266]
#### Description of the Bug
Wurst-Bot seems to not be able to connect to any servers using wurst v4.6

#### How to Reproduce the Bug
This happens on offline and online servers just type join (IP) it does not work here are the logs
```
Wurst-Bot v4.6
Type "help" for a list of commands.
join localhost
[11:39:25] [Client thread/INFO]: Connecting to localhost, 25565
Joined localhost as Player527
Exception in thread "Server Connector #1" java.lang.NoClassDefFoundError: io/netty/channel/epoll/Epoll
        at net.minecraft.network.NetworkManager.createNetworkManagerAndConnect(NetworkManager.java:381)
        at net.minecraft.client.multiplayer.GuiConnecting$1.run(GuiConnecting.java:65)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.epoll.Epoll
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more
```
#### Other Information
- Wurst Client version: 4.6
- Operating system: Windows 10
Wurst bot launcher 1.0.1

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by GlitchHead** [comment]
I found a fix to this issue but you might want to update the wurst bot releases i deleted all of my libarys in my .minecraft and restarted the game it then downloaded new ones i copyed all of the new ones to wurst-bot_lib and then changed the classpaths to all of the .jars using
```
java -classpath ".\*;Wurst-Bot_lib\*" tk.wurst_client.bot.WurstBot
```
also something else with wurst bot could you update .follow and .protect with the new AI additions you added to .goto?
