### ISSUE TITLE
AntiAFK crashes v5

### ISSUE THREAD

**Issue by BlackjaiRL** [Wurst-Imperium/Wurst-Client-Bugs#290]
To submit a new bug report, fill out the following form.
-->

#### Briefly describe what is happening.
Game crashes when using AntiAFK

#### How can someone reliably cause this bug to happen?
When you uses AntiAFK , it walks for a few seconds , then it turned into grey screen then crashes

### What Minecraft versions are affected by this bug?

- [X ] MC 1.11
- [ ] MC 1.10
- [ ] MC 1.9
- [ ] MC 1.8

#### What operating systems are affected by this bug?
- [X ] Windows 10
- [ ] Windows 8 / 8.1
- [ ] Windows 7
- [ ] Linux
- [ ] Mac

#### Paste your crash report below.

```
---- Wurst Client Crash Report ----
Go to https://www.wurst-client.tk/bugs/ to report this crash.
// Sorry :(

Time: 17年1月8日 上午1:03
Description: Toggling Wurst mod

java.lang.IndexOutOfBoundsException: -100
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at tk.wurst_client.ai.PathProcessor.releaseControls(PathProcessor.java:63)
	at tk.wurst_client.ai.PathProcessor.stop(PathProcessor.java:46)
	at tk.wurst_client.ai.GoRandomAI.stop(GoRandomAI.java:73)
	at tk.wurst_client.features.mods.AntiAfkMod.onDisable(AntiAfkMod.java:40)
	at tk.wurst_client.features.mods.Mod.setEnabled(Mod.java:171)
	at tk.wurst_client.features.mods.Mod.toggle(Mod.java:242)
	at tk.wurst_client.features.mods.Mod.doPrimaryAction(Mod.java:127)
	at tk.wurst_client.navigator.gui.NavigatorMainScreen.onMouseClick(NavigatorMainScreen.java:98)
	at tk.wurst_client.navigator.gui.NavigatorScreen.mouseClicked(NavigatorScreen.java:55)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:596)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:565)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1785)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1103)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:115)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at tk.wurst_client.ai.PathProcessor.releaseControls(PathProcessor.java:63)
	at tk.wurst_client.ai.PathProcessor.stop(PathProcessor.java:46)
	at tk.wurst_client.ai.GoRandomAI.stop(GoRandomAI.java:73)
	at tk.wurst_client.features.mods.AntiAfkMod.onDisable(AntiAfkMod.java:40)

-- Affected mod --
Details:
	Mod name: AntiAFK
	Attempted action: Disable
Stacktrace:
	at tk.wurst_client.features.mods.Mod.setEnabled(Mod.java:171)
	at tk.wurst_client.features.mods.Mod.toggle(Mod.java:242)
	at tk.wurst_client.features.mods.Mod.doPrimaryAction(Mod.java:127)
	at tk.wurst_client.navigator.gui.NavigatorMainScreen.onMouseClick(NavigatorMainScreen.java:98)
	at tk.wurst_client.navigator.gui.NavigatorScreen.mouseClicked(NavigatorScreen.java:55)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:596)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:565)

-- Affected screen --
Details:
	Screen name: tk.wurst_client.navigator.gui.NavigatorMainScreen

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Blackjai_RL'/1578731, l='MpServer', x=10602.30, y=119.00, z=-18000.50]]
	Chunk stats: MultiplayerChunkCache: 82, 82
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 240243826 game time, 240262401 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityPig['§e§l1X §6§lPIG'/1578732, l='MpServer', x=10604.47, y=117.00, z=-17999.94], EntityPlayerSP['Blackjai_RL'/1578731, l='MpServer', x=10602.30, y=119.00, z=-18000.50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.11-SNAPSHOT:b728aea:1216) <- TacoSpigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2915)
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:115)

-- System Details --
Details:
	Minecraft Version: 1.11
	Wurst Client Version: 5.5 (latest: 5.5)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 155694056 bytes (148 MB) / 406581248 bytes (387 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst Client for Minecraft 1.11
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
```

**Comment by redsoxno10** [comment]
I got the same thing
here is my crash report:
```
---- Wurst Client Crash Report ----
Go to https://www.wurst-client.tk/bugs/ to report this crash.
// I let you down. Sorry :(

Time: 1/17/17 6:53 PM
Description: Firing Wurst event

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at tk.wurst_client.ai.RandomPathFinder.setCurrentToRandomNode(RandomPathFinder.java:69)
	at tk.wurst_client.ai.RandomPathFinder.formatPath(RandomPathFinder.java:88)
	at tk.wurst_client.ai.GoRandomAI.update(GoRandomAI.java:41)
	at tk.wurst_client.features.mods.AntiAfkMod.onUpdate(AntiAfkMod.java:62)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:53)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:236)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2023)
	at net.minecraft.world.World.updateEntity(World.java:1993)
	at net.minecraft.world.World.updateEntities(World.java:1836)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1876)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1103)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:115)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at tk.wurst_client.ai.RandomPathFinder.setCurrentToRandomNode(RandomPathFinder.java:69)
	at tk.wurst_client.ai.RandomPathFinder.formatPath(RandomPathFinder.java:88)
	at tk.wurst_client.ai.GoRandomAI.update(GoRandomAI.java:41)
	at tk.wurst_client.features.mods.AntiAfkMod.onUpdate(AntiAfkMod.java:62)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
	Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
	at tk.wurst_client.events.EventManager.fire(EventManager.java:53)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:236)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2023)
	at net.minecraft.world.World.updateEntity(World.java:1993)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 11628
	Entity Name: Sudomeapizza
	Entity's Exact location: -1724.53, 67.00, 6628.56
	Entity's Block location: World: (-1725,67,6628), Chunk: (at 3,4,4 in -108,414; contains blocks -1728,0,6624 to -1713,255,6639), Region: (-4,12; contains chunks -128,384 to -97,415, blocks -2048,0,6144 to -1537,255,6655)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1836)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Sudomeapizza'/11628, l='MpServer', x=-1724.53, y=67.00, z=6628.56]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1736,69,6624), Chunk: (at 8,4,0 in -109,414; contains blocks -1744,0,6624 to -1729,255,6639), Region: (-4,12; contains chunks -128,384 to -97,415, blocks -2048,0,6144 to -1537,255,6655)
	Level time: 325286953 game time, 325748407 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 10 total; [EntityPlayerSP['Sudomeapizza'/11628, l='MpServer', x=-1724.53, y=67.00, z=6628.56], EntityOtherPlayerMP['§bAuction House'/125, l='MpServer', x=58.47, y=81.00, z=7.59], EntityOtherPlayerMP['§bShop'/262, l='MpServer', x=58.34, y=81.00, z=-6.63], EntityRabbit['§e§lx1 Rabbit'/73706367, l='MpServer', x=-1721.00, y=68.00, z=6613.44], EntityOtherPlayerMP['_ChubbyChicken_'/70666297, l='MpServer', x=-55.96, y=80.00, z=1.81], EntityOtherPlayerMP['EthanP0214'/72650306, l='MpServer', x=-85.44, y=80.50, z=32.47], EntityOtherPlayerMP['THEGRONK_87'/72853715, l='MpServer', x=-56.20, y=80.36, z=2.72], EntitySkeleton['Skeleton'/73847628, l='MpServer', x=-1706.50, y=31.00, z=6625.50], EntitySkeleton['Skeleton'/73847629, l='MpServer', x=-1702.50, y=31.00, z=6624.50], EntityItem['item.tile.sapling.spruce'/74613571, l='MpServer', x=-1720.14, y=79.04, z=6636.71]]
	Retry entities: 0 total; []
	Server brand: exaCord (git:BungeeCord-Bootstrap:1.11-SNAPSHOT:5a1da1f:120) <- PaperSpi
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2915)
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:115)

-- System Details --
Details:
	Minecraft Version: 1.11
	Wurst Client Version: 5.5 (latest: 5.5)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 189379800 bytes (180 MB) / 1430781952 bytes (1364 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	IntCache: cache: 0, tcache: 12, allocated: 13, tallocated: 95
	Launched Version: Wurst Client for Minecraft 1.11
	LWJGL: 2.9.4
	OpenGL: GeForce GT 730/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX(tm)-4300 Quad-Core Processor 
```
