### ISSUE TITLE
Smash Nuker Client Crash 1.11.2 Wurst Ver. 5.5

### ISSUE THREAD

**Issue by SmashBlocks** [Wurst-Imperium/Wurst-Client-Bugs#291]
#### Briefly describe what is happening.

Nuker (Smash mode) crashes client

#### How can someone reliably cause this bug to happen?

Enter the game with no active mods, open a server, activate smash nuker, and then the game will crash
[Wurst Crash Video.zip](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/691753/Wurst.Crash.Video.zip)
P.S. The file was too large to upload so i had to compress it.
#### What Minecraft versions are affected by this bug?

- [X] MC 1.11
- [ ] MC 1.10
- [ ] MC 1.9
- [ ] MC 1.8

#### What operating systems are affected by this bug?

- [X] Windows 10
- [ ] Windows 8 / 8.1
- [ ] Windows 7
- [ ] Linux
- [ ] Mac

#### Paste your crash report below.

```
---- Wurst Client Crash Report ----
Go to https://www.wurst-client.tk/bugs/ to report this crash.
// Shall we play a game?

Time: 1/7/17 2:52 PM
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
	at net.minecraft.world.World.isOutsideBuildHeight(World.java:258)
	at net.minecraft.world.World.getBlockState(World.java:937)
	at tk.wurst_client.features.mods.NukerMod.find(NukerMod.java:270)
	at tk.wurst_client.features.mods.NukerMod.onUpdate(NukerMod.java:134)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:53)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:236)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2023)
	at net.minecraft.world.World.updateEntity(World.java:1993)
	at net.minecraft.world.World.updateEntities(World.java:1836)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1876)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1103)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:115)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.isOutsideBuildHeight(World.java:258)
	at net.minecraft.world.World.getBlockState(World.java:937)
	at tk.wurst_client.features.mods.NukerMod.find(NukerMod.java:270)
	at tk.wurst_client.features.mods.NukerMod.onUpdate(NukerMod.java:134)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
	Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
	at tk.wurst_client.events.EventManager.fire(EventManager.java:53)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:236)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2023)
	at net.minecraft.world.World.updateEntity(World.java:1993)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 6227
	Entity Name: SmashBlocksGamer
	Entity's Exact location: -63.83, 62.94, -261.02
	Entity's Block location: World: (-64,62,-262), Chunk: (at 0,3,10 in -4,-17; contains blocks -64,0,-272 to -49,255,-257), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.06, -0.08, -0.10
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1836)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['SmashBlocksGamer'/6227, l='MpServer', x=-63.83, y=62.94, z=-261.02]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-76,64,-148), Chunk: (at 4,4,12 in -5,-10; contains blocks -80,0,-160 to -65,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 330919090 game time, 297573620 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 85 total; [EntityPlayerSP['SmashBlocksGamer'/6227, l='MpServer', x=-63.83, y=62.94, z=-261.02], EntityBat['Bat'/5634, l='MpServer', x=-135.66, y=44.00, z=-239.29], EntityZombie['Zombie'/6403, l='MpServer', x=-33.50, y=68.00, z=-193.50], EntitySkeleton['Skeleton'/6404, l='MpServer', x=-25.50, y=68.00, z=-197.50], EntityZombie['Zombie'/6673, l='MpServer', x=-110.55, y=65.00, z=-296.74], EntityZombie['Zombie'/6674, l='MpServer', x=-125.19, y=65.00, z=-288.78], EntityCreeper['Creeper'/6930, l='MpServer', x=10.50, y=67.00, z=-198.50], EntityCreeper['Creeper'/6931, l='MpServer', x=11.50, y=67.00, z=-194.50], EntitySkeleton['Skeleton'/6934, l='MpServer', x=-15.50, y=69.00, z=-222.73], EntityWitch['Witch'/6428, l='MpServer', x=-76.34, y=16.00, z=-283.49], EntitySpider['Spider'/6947, l='MpServer', x=-30.50, y=63.00, z=-300.50], EntityBat['Bat'/5412, l='MpServer', x=-102.75, y=19.68, z=-212.49], EntitySheep['Sheep'/42, l='MpServer', x=-144.27, y=66.00, z=-194.50], EntitySkeleton['Skeleton'/6447, l='MpServer', x=-9.50, y=69.00, z=-186.50], EntitySkeleton['Skeleton'/6448, l='MpServer', x=-7.50, y=69.00, z=-186.50], EntityBat['Bat'/6707, l='MpServer', x=-26.45, y=34.76, z=-205.47], EntityChicken['Chicken'/65, l='MpServer', x=-115.48, y=69.00, z=-227.86], EntitySkeleton['Skeleton'/6213, l='MpServer', x=-7.50, y=35.00, z=-188.50], EntityEnderman['Enderman'/6983, l='MpServer', x=-7.50, y=67.00, z=-328.50], EntityCreeper['Creeper'/5705, l='MpServer', x=-34.48, y=39.00, z=-214.21], EntityZombie['Zombie'/6987, l='MpServer', x=-33.50, y=64.00, z=-238.50], EntityZombie['Zombie'/5708, l='MpServer', x=-32.93, y=39.00, z=-206.30], EntityBat['Bat'/5969, l='MpServer', x=-131.16, y=12.00, z=-216.25], EntityItem['item.item.egg'/6226, l='MpServer', x=-69.74, y=64.00, z=-208.51], EntityCreeper['Creeper'/6739, l='MpServer', x=-131.50, y=29.00, z=-309.50], EntityBat['Bat'/5972, l='MpServer', x=-101.43, y=44.49, z=-244.48], EntityCreeper['Creeper'/6740, l='MpServer', x=-130.50, y=29.00, z=-312.50], EntityBat['Bat'/5973, l='MpServer', x=-101.02, y=44.07, z=-243.06], EntityBat['Bat'/5974, l='MpServer', x=-107.29, y=41.00, z=-234.28], EntityZombie['Zombie'/6744, l='MpServer', x=-43.46, y=65.00, z=-193.75], EntityPig['Pig'/89, l='MpServer', x=-86.54, y=64.00, z=-208.11], EntityPig['Pig'/90, l='MpServer', x=-87.93, y=64.00, z=-208.93], EntityPig['Pig'/91, l='MpServer', x=-82.74, y=64.00, z=-208.51], EntitySkeleton['Skeleton'/6750, l='MpServer', x=-44.50, y=37.00, z=-260.50], EntitySheep['Sheep'/6239, l='MpServer', x=-145.39, y=64.00, z=-272.23], EntityChicken['Chicken'/6240, l='MpServer', x=-47.16, y=67.00, z=-288.43], EntityItem['item.item.egg'/6241, l='MpServer', x=-39.19, y=68.00, z=-285.82], EntityCreeper['Creeper'/6753, l='MpServer', x=-110.50, y=68.00, z=-319.50], EntityZombie['Zombie'/7009, l='MpServer', x=-136.50, y=39.00, z=-240.50], EntitySheep['Sheep'/6242, l='MpServer', x=-28.46, y=57.00, z=-296.23], EntityZombie['Zombie'/7010, l='MpServer', x=-137.50, y=39.00, z=-243.50], EntitySkeleton['Skeleton'/7011, l='MpServer', x=-140.50, y=39.00, z=-242.50], EntitySpider['Spider'/6756, l='MpServer', x=-62.30, y=64.00, z=-234.16], EntitySkeleton['Skeleton'/7012, l='MpServer', x=-142.50, y=39.00, z=-233.76], EntitySkeleton['Skeleton'/6758, l='MpServer', x=-54.50, y=64.00, z=-238.50], EntityChicken['Chicken'/106, l='MpServer', x=-69.54, y=64.00, z=-209.92], EntityChicken['Chicken'/107, l='MpServer', x=-69.46, y=64.00, z=-210.51], EntityChicken['Chicken'/108, l='MpServer', x=-71.94, y=64.00, z=-210.54], EntityChicken['Chicken'/109, l='MpServer', x=-71.52, y=64.00, z=-210.54], EntityCreeper['Creeper'/6256, l='MpServer', x=-115.23, y=67.00, z=-181.48], EntityCow['Cow'/120, l='MpServer', x=-50.92, y=70.00, z=-179.00], EntityCow['Cow'/121, l='MpServer', x=-51.93, y=70.00, z=-178.08], EntityCreeper['Creeper'/6521, l='MpServer', x=-141.57, y=17.00, z=-228.20], EntityCow['Cow'/122, l='MpServer', x=-46.08, y=70.00, z=-178.08], EntityCow['Cow'/130, l='MpServer', x=-47.07, y=70.00, z=-178.80], EntityCow['Cow'/131, l='MpServer', x=-47.27, y=70.00, z=-180.93], EntityCow['Cow'/132, l='MpServer', x=-47.22, y=70.00, z=-179.81], EntityCow['Cow'/133, l='MpServer', x=-46.08, y=70.00, z=-180.93], EntityCow['Cow'/134, l='MpServer', x=-46.10, y=70.00, z=-179.97], EntityBat['Bat'/6791, l='MpServer', x=-96.17, y=23.47, z=-236.58], EntityBat['Bat'/6792, l='MpServer', x=-104.75, y=22.00, z=-214.25], EntityCow['Cow'/138, l='MpServer', x=-25.45, y=46.00, z=-242.45], EntityDonkey['Donkey'/142, l='MpServer', x=-27.64, y=65.00, z=-226.56], EntityItem['item.item.egg'/3215, l='MpServer', x=-11.61, y=73.00, z=-239.08], EntityChicken['Chicken'/150, l='MpServer', x=-11.12, y=73.00, z=-239.48], EntityBat['Bat'/7074, l='MpServer', x=-80.12, y=53.13, z=-276.93], EntityBat['Bat'/7075, l='MpServer', x=-65.25, y=51.22, z=-292.55], EntityBat['Bat'/7076, l='MpServer', x=-75.75, y=54.08, z=-282.50], EntityZombie['Zombie'/6822, l='MpServer', x=-25.50, y=63.00, z=-303.50], EntitySpider['Spider'/6824, l='MpServer', x=-129.50, y=38.00, z=-242.50], EntityZombieVillager['Zombie Villager'/6839, l='MpServer', x=-12.80, y=69.00, z=-188.56], EntitySkeleton['Skeleton'/6841, l='MpServer', x=7.50, y=64.00, z=-270.50], EntityItem['item.item.egg'/187, l='MpServer', x=-69.19, y=64.00, z=-210.61], EntityBat['Bat'/6589, l='MpServer', x=-119.61, y=32.59, z=-215.95], EntityItem['item.item.egg'/6590, l='MpServer', x=-70.67, y=64.00, z=-209.91], EntityCreeper['Creeper'/6846, l='MpServer', x=-19.50, y=65.00, z=-211.50], EntityBat['Bat'/6858, l='MpServer', x=-137.75, y=41.10, z=-240.25], EntityCreeper['Creeper'/4310, l='MpServer', x=-2.50, y=34.00, z=-177.50], EntityCreeper['Creeper'/6110, l='MpServer', x=-31.21, y=34.00, z=-219.50], EntityZombie['Zombie'/5608, l='MpServer', x=-86.44, y=51.00, z=-257.26], EntityItem['item.item.egg'/3307, l='MpServer', x=-115.31, y=69.00, z=-227.38], EntityEnderman['Enderman'/6637, l='MpServer', x=-66.50, y=52.00, z=-291.50], EntityCreeper['Creeper'/4078, l='MpServer', x=-138.50, y=17.00, z=-227.50], EntityCreeper['Creeper'/5614, l='MpServer', x=7.19, y=35.00, z=-197.33], EntityZombie['Zombie'/5366, l='MpServer', x=-134.50, y=17.00, z=-230.18]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2915)
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:115)

-- System Details --
Details:
	Minecraft Version: 1.11
	Wurst Client Version: 5.5 (latest: 5.5)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 86313960 bytes (82 MB) / 312971264 bytes (298 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Wurst Client for Minecraft 1.11
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
```

**Comment by Alexander01998** [comment]
Please try to reproduce the crash on [this development build](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/699776/Wurst-Client-dev-build.zip) and tell me if it still crashes.
If it does, post the crash report below (a video is NOT required this time).

**Comment by SmashBlocks** [comment]
I was unable to use the developer build, the wurst auto updater updated it to 5.5, can the auto updater be disabled?
