### ISSUE TITLE
Crash involving Ticking screen(Crash report provided)

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client-Bugs#3]
#### Description of the Bug
Crash involving Ticking screen(Crash report provided)

#### How to Reproduce the Bug
```
---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// I just don't know what went wrong :(

Time: 5/1/16 2:04 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at net.minecraft.network.NetworkManager$InboundHandlerTuplePacketListener.access$0(NetworkManager.java:535)
	at net.minecraft.network.NetworkManager.flushOutboundQueue(NetworkManager.java:311)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:326)
	at net.minecraft.client.multiplayer.GuiConnecting.updateScreen(GuiConnecting.java:111)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1853)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1154)
	at net.minecraft.client.Minecraft.run(Minecraft.java:455)
	at net.minecraft.client.main.Main.main(Main.java:115)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.network.NetworkManager$InboundHandlerTuplePacketListener.access$0(NetworkManager.java:535)
	at net.minecraft.network.NetworkManager.flushOutboundQueue(NetworkManager.java:311)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:326)
	at net.minecraft.client.multiplayer.GuiConnecting.updateScreen(GuiConnecting.java:111)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.multiplayer.GuiConnecting
Stacktrace:
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1853)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1154)
	at net.minecraft.client.Minecraft.run(Minecraft.java:455)
	at net.minecraft.client.main.Main.main(Main.java:115)

-- System Details --
Details:
	Minecraft Version: 1.9
	Wurst Client Version: 3.0 (latest: 3.0)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 237827336 bytes (226 MB) / 323547136 bytes (308 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.9.X with Wurst Client
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.4.0 - Build 20.19.15.4364, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Atom(TM) x5-Z8300 CPU @ 1.44GHz
 ```

#### Other Information
- Wurst Client version: 3.0
- Operating system: Windows 10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by Alexander01998** [comment]
Please fill out the "Wurst Client version" and "Operating system" sections.

**Comment by Alexander01998** [comment]
Please include a list of the necessary steps to reproduce this bug. What did you do just before the bug occurred? What does one need to do in order for this bug to occur?
