### ISSUE TITLE
HELP ME! BUYG DETECTED WICTH USING KILLAURALEGIT!

### ISSUE THREAD

**Issue by Juan123Gamer** [Wurst-Imperium/Wurst-Client-Bugs#31]
> This is an auto-generated error report for the [Wurst Client](https://www.wurst-client.tk).

# Description
An error occurred while processing events.
Event type: UpdateEvent

# Stacktrace
```
java.lang.NullPointerException
	at net.minecraft.entity.Entity.getDistanceToEntity(Entity.java:1351)
	at tk.wurst_client.mods.KillauraLegitMod.onUpdate(KillauraLegitMod.java:56)
	at tk.wurst_client.events.EventManager.fireUpdate(EventManager.java:123)
	at tk.wurst_client.events.EventManager.fireEvent(EventManager.java:35)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:131)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1884)
	at net.minecraft.world.World.updateEntity(World.java:1853)
	at net.minecraft.world.World.updateEntities(World.java:1702)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2305)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1200)
	at net.minecraft.client.Minecraft.run(Minecraft.java:380)
	at net.minecraft.client.main.Main.main(Main.java:129)

```

# System details
- OS: Windows 8.1 (x86)
- Java version: 1.8.0_91 (Oracle Corporation)
- Wurst version: 2.21 (latest: 2.21)
- Timestamp: 2016.05.14-08:00:47

**Comment by mcccs** [comment]
What were you doing before it crashed?
