### ISSUE TITLE
Realms Bug

### ISSUE THREAD

**Issue by TFahami** [Wurst-Imperium/Wurst-Client-Bugs#43]
#### Description of the Bug
When going into the realms menu the game crashes and shows me the crash report.

#### How to Reproduce the Bug
The bug occurs(at least for me) whenever i press the realms button on the title screen.

#### Other Information
- Wurst Client version: 3.2 (1.9.x)
- Operating system: windows 7 Home Premium

Crash Log:

---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Don't be sad, have a hug! <3

Time: 5/20/16 8:18 PM
Description: Updating screen events

java.lang.NoClassDefFoundError: net/minecraft/realms/RealmsServerStatusPinger
	at com.mojang.realmsclient.RealmsMainScreen.<clinit>(RealmsMainScreen.java:53)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraft.realms.RealmsBridge.switchToRealms(RealmsBridge.java:21)
	at net.minecraft.client.gui.GuiMainMenu.switchToRealms(GuiMainMenu.java:345)
	at net.minecraft.client.gui.GuiMainMenu.actionPerformed(GuiMainMenu.java:317)
	at tk.wurst_client.gui.main.GuiWurstMainMenu.actionPerformed(GuiWurstMainMenu.java:167)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:490)
	at net.minecraft.client.gui.GuiMainMenu.mouseClicked(GuiMainMenu.java:609)
	at tk.wurst_client.gui.main.GuiWurstMainMenu.mouseClicked(GuiWurstMainMenu.java:404)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:595)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:564)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1774)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1095)
	at net.minecraft.client.Minecraft.run(Minecraft.java:396)
	at net.minecraft.client.main.Main.main(Main.java:115)
Caused by: java.lang.ClassNotFoundException: net.minecraft.realms.RealmsServerStatusPinger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mojang.realmsclient.RealmsMainScreen.<clinit>(RealmsMainScreen.java:53)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraft.realms.RealmsBridge.switchToRealms(RealmsBridge.java:21)
	at net.minecraft.client.gui.GuiMainMenu.switchToRealms(GuiMainMenu.java:345)
	at net.minecraft.client.gui.GuiMainMenu.actionPerformed(GuiMainMenu.java:317)
	at tk.wurst_client.gui.main.GuiWurstMainMenu.actionPerformed(GuiWurstMainMenu.java:167)
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:490)
	at net.minecraft.client.gui.GuiMainMenu.mouseClicked(GuiMainMenu.java:609)
	at tk.wurst_client.gui.main.GuiWurstMainMenu.mouseClicked(GuiWurstMainMenu.java:404)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:595)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:564)

-- Affected screen --
Details:
	Screen name: tk.wurst_client.gui.main.GuiWurstMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1774)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1095)
	at net.minecraft.client.Minecraft.run(Minecraft.java:396)
	at net.minecraft.client.main.Main.main(Main.java:115)

-- System Details --
Details:
	Minecraft Version: 1.9
	Wurst Client Version: 3.2 (latest: 3.2)
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 187496440 bytes (178 MB) / 307773440 bytes (293 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 670M/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.72, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: <unknown>

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
Not happening for me.

![screen shot 2016-05-21 at 12 50 33](https://cloud.githubusercontent.com/assets/11584045/15447675/a1f562fc-1f52-11e6-896d-06bb15ef4c21.png)

**Comment by TFahami** [comment]
It might be diffrent on mac

**Comment by mcccs** [comment]
I'm on Mac too.

**Comment by mcccs** [comment]
I don't think it matters.
