### ISSUE TITLE
help me wurst

### ISSUE THREAD

**Issue by prococuk265** [Wurst-Imperium/Wurst-Client-Bugs#63]
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/Minecraft : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:39)
 HELP ME CRASH

**Comment by mcccs** [comment]
https://www.wurst-client.tk/wiki/Java_8/

Just download and run the jar launcher: [DL at minecraft.net](http://s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.jar)

Didn't work? [Download Java](https://java.com/en/download/mac_download.jsp) and run that launcher again.

**Comment by mcccs** [comment]
@Alexander01998 I wonder why "Java 8 is not installed!" window doesn't open.

**Comment by prococuk265** [comment]
Im no premium no minecraft original :((

**Comment by prococuk265** [comment]
IM NO PREMİUM !

**Comment by prococuk265** [comment]
My Premium Account No

**Comment by prococuk265** [comment]
HELP ME

**Comment by mcccs** [comment]
Did you download Java? https://java.com/en/download/mac_download.jsp

**Comment by prococuk265** [comment]
ım windows

**Comment by mcccs** [comment]
Download Java for windows: http://javadl.oracle.com/webapps/download/AutoDL?BundleId=210183

**Comment by optifinewalrus** [comment]
hey i have an issue with wurst
whenevber i move, it keeps bringing up the page when i can choose the hacks how do i disable it?
