### ISSUE TITLE
HELP ME PLS CRASH

### ISSUE THREAD

**Issue by prococuk265** [Wurst-Imperium/Wurst-Client-Bugs#64]
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/Minecraft : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(Main.java:39)
Help me please

**Comment by mcccs** [comment]
Close this issue, because this is
## DUPLICATE: #63 
![dupli](https://cloud.githubusercontent.com/assets/11584045/15435554/a30d6456-1ec5-11e6-83d3-787a691381ea.PNG)
STOP OPENING MULTIPLE ISSUES.
