### ISSUE TITLE
Wurst Kill Aura Legit Bug

### ISSUE THREAD

**Issue by Leosteon** [Wurst-Imperium/Wurst-Client-Bugs#84]
#### Description of the Bug
While playing on a Sky Wars server, i activated Kill Aura Legit but then a bug screen popped making me unable to play the game. When i say "Back to game" the screen either doesn't close or closes but gets back shortly later.

#### How to Reproduce the Bug
Activate Kill Aura Legit
#### Other Information
- Wurst Client version: Wurst 3.3
- Operating system: 

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
You have to glve the log after you click the View Bug button.

**Comment by Leosteon** [comment]
> This is an auto-generated error report for the [Wurst Client](
https://www.wurst-client.tk).

# Description
An error occurred while processing events.
Event type: UpdateEvent

# Stacktrace
```
java.lang.NullPointerException
at net.minecraft.entity.Entity.getDistanceToEntity(Entity.java:1351)
at tk.wurst_client.mods.KillauraLegitMod.onUpdate(KillauraLegitMod.java:56)
at tk.wurst_client.events.EventManager.fireUpdate(EventManager.java:123)
at tk.wurst_client.events.EventManager.fireEvent(EventManager.java:35)
at
net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:131)
at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1884)
at net.minecraft.world.World.updateEntity(World.java:1853)
at net.minecraft.world.World.updateEntities(World.java:1702)
at net.minecraft.client.Minecraft.runTick(Minecraft.java:2305)
at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1200)
at net.minecraft.client.Minecraft.run(Minecraft.java:380)
at net.minecraft.client.main.Main.main(Main.java:129)

```

# System details
- OS: Windows 7 (x86)
- Java version: 1.8.0_66 (Oracle Corporation)
- Wurst version: 2.21.2 (latest: 2.21.2)
- Timestamp: 2016.06.11-02:53:17

**Comment by ThaRealMrGong** [comment]
Might be caused by hypixel spawning fake entities. Seen null pointers on a vanilla 1.9 client

**Comment by Redstonefist** [comment]
What you have to do to fix it, install a later minecraft version for wurst and go on the later version of minecraft wurst, turn off kill-aura legit (it will not show the bug thing on the screen in that version). Go back in the older version and ta da! Fixed!
