### ISSUE TITLE
When I open the game, I will try to join a server, and the game crashes.

### ISSUE THREAD

**Issue by XxZaeKillerxX** [Wurst-Imperium/Wurst-Client-Bugs#92]
This problem will happen with any server. I expect me to login to the server without problems, but it just crashes.
Start The Game>Choose Wurst Client>Click Play>Click Multiplayer>Choose Server>Join Server>Game Crash

My Wurst Client is 1.9.X and my operating system is Ubuntu Linux. I do not believe the RAM is the problem as I have tried 1 RAM, 2 RAM, 4 RAM, 10 RAM, and the result is always the same.

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

Crash Report:

```
 ---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Immer weiter gehen, nicht stehen bleiben!

Time: 6/16/16 10:46 AM
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
	at net.minecraft.world.World.isValid(World.java:250)
	at net.minecraft.world.World.getBlockState(World.java:855)
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:277)
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:119)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:201)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1945)
	at net.minecraft.world.World.updateEntity(World.java:1914)
	at net.minecraft.world.World.updateEntities(World.java:1764)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1878)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1109)
	at net.minecraft.client.Minecraft.run(Minecraft.java:396)
	at net.minecraft.client.main.Main.main(Main.java:115)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.World.isValid(World.java:250)
	at net.minecraft.world.World.getBlockState(World.java:855)
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:277)
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:119)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
	Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:201)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1945)
	at net.minecraft.world.World.updateEntity(World.java:1914)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 320565
	Entity Name: XxZaeKillerxX
	Entity's Exact location: 0.50, 20.50, 1.50
	Entity's Block location: World: (0,20,1), Chunk: (at 0,1,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1764)

-- Affected level --
Details:
	Level name: MpServer
	All players: 10 total; [EntityPlayerSP['XxZaeKillerxX'/320565, l='MpServer', x=0.50, y=20.50, z=1.50], EntityOtherPlayerMP['scorchednyki'/319392, l='MpServer', x=0.50, y=20.50, z=1.50], EntityOtherPlayerMP['TBNRjohnathon'/314786, l='MpServer', x=9.47, y=19.67, z=18.76], EntityOtherPlayerMP['Duhduhducky'/291882, l='MpServer', x=-1.83, y=20.00, z=20.17], EntityOtherPlayerMP['littlemaster77'/319174, l='MpServer', x=-2.80, y=20.00, z=19.81], EntityOtherPlayerMP['cracycreeper3'/294288, l='MpServer', x=-8.28, y=20.00, z=5.47], EntityOtherPlayerMP['georgeman5054'/316202, l='MpServer', x=-12.41, y=20.17, z=11.64], EntityOtherPlayerMP['mr_dutchy2001'/309138, l='MpServer', x=-16.66, y=21.00, z=20.06], EntityOtherPlayerMP['2002strike'/317441, l='MpServer', x=-16.22, y=21.00, z=15.69], EntityOtherPlayerMP['KrystalDai'/305718, l='MpServer', x=-17.66, y=21.00, z=14.56]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,20,1), Chunk: (at 0,1,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 54843562 game time, 120000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntityPlayerSP['XxZaeKillerxX'/320565, l='MpServer', x=0.50, y=20.50, z=1.50], EntityOtherPlayerMP['scorchednyki'/319392, l='MpServer', x=0.50, y=20.50, z=1.50], EntityOtherPlayerMP['littlemaster77'/319174, l='MpServer', x=-2.80, y=20.00, z=19.81], EntityOtherPlayerMP['2002strike'/317441, l='MpServer', x=-16.22, y=21.00, z=15.69], EntityArmorStand['§f§l§oThe §2§l§oVoter §f§l§oCrate'/203, l='MpServer', x=-19.22, y=21.50, z=15.56], EntityOtherPlayerMP['TBNRjohnathon'/314786, l='MpServer', x=9.47, y=19.67, z=18.76], EntityArmorStand['§f§l§oThe §1§l§oRankup §f§l§oCrate'/204, l='MpServer', x=-19.59, y=21.50, z=25.44], EntityOtherPlayerMP['Duhduhducky'/291882, l='MpServer', x=-1.83, y=20.00, z=20.17], EntityArmorStand['§f§o§n§lThe §5§l§n§oPurple §f§o§n§lCrate'/205, l='MpServer', x=-19.28, y=21.50, z=20.63], EntityOtherPlayerMP['littlemaster77'/319174, l='MpServer', x=-2.80, y=20.00, z=19.81], EntityOtherPlayerMP['cracycreeper3'/294288, l='MpServer', x=-8.28, y=20.00, z=5.47], EntityOtherPlayerMP['georgeman5054'/316202, l='MpServer', x=-12.41, y=20.17, z=11.64], EntityOtherPlayerMP['cracycreeper3'/294288, l='MpServer', x=-8.28, y=20.00, z=5.47], EntityOtherPlayerMP['mr_dutchy2001'/309138, l='MpServer', x=-16.66, y=21.00, z=20.06], EntityOtherPlayerMP['mr_dutchy2001'/309138, l='MpServer', x=-16.66, y=21.00, z=20.06], EntityOtherPlayerMP['2002strike'/317441, l='MpServer', x=-16.22, y=21.00, z=15.69], EntityOtherPlayerMP['KrystalDai'/305718, l='MpServer', x=-17.66, y=21.00, z=14.56], EntityOtherPlayerMP['scorchednyki'/319392, l='MpServer', x=0.50, y=20.50, z=1.50], EntityOtherPlayerMP['TBNRjohnathon'/314786, l='MpServer', x=9.47, y=19.67, z=18.76], EntityOtherPlayerMP['Duhduhducky'/291882, l='MpServer', x=-1.83, y=20.00, z=20.17], EntityOtherPlayerMP['georgeman5054'/316202, l='MpServer', x=-12.41, y=20.17, z=11.64], EntityArmorStand['§dWelcome to §5§lPurple Prison'/319732, l='MpServer', x=0.47, y=22.47, z=5.13], EntityArmorStand['§fTo get started, type §5§l/warp a'/319733, l='MpServer', x=0.47, y=22.22, z=5.13], EntityArmorStand['§7§m-------------------------------------'/319734, l='MpServer', x=0.47, y=21.97, z=5.13], EntityOtherPlayerMP['KrystalDai'/305718, l='MpServer', x=-17.66, y=21.00, z=14.56], EntityArmorStand['§fBe careful! You can PvP §5§lAhead!'/319735, l='MpServer', x=0.47, y=21.72, z=5.13], EntityArmorStand['§7§m-------------------------------------'/319731, l='MpServer', x=0.47, y=22.72, z=5.13], EntityArmorStand['§7§m-------------------------------------'/319740, l='MpServer', x=0.47, y=20.47, z=5.13], EntityArmorStand['§fYou can also donate for awesome stuff with §5§l/BUY'/319736, l='MpServer', x=0.47, y=21.47, z=5.13], EntityArmorStand['§7§m-------------------------------------'/319737, l='MpServer', x=0.47, y=21.22, z=5.13], EntityArmorStand['§fStore: §d§l§nWWW.BUY.PURPLEPRISON.NET'/319738, l='MpServer', x=0.47, y=20.97, z=5.13], EntityArmorStand['§fForums: §d§l§nWWW.PURPLEPRISON.CO'/319739, l='MpServer', x=0.47, y=20.72, z=5.13]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:442)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2907)
	at net.minecraft.client.Minecraft.run(Minecraft.java:417)
	at net.minecraft.client.main.Main.main(Main.java:115)

-- System Details --
Details:
	Minecraft Version: 1.9
	Wurst Client Version: 3.4 (latest: 3.4)
	Operating System: Linux (amd64) version 4.2.0-36-generic
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 121495768 bytes (115 MB) / 291704832 bytes (278 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.9.X with Wurst Client
	LWJGL: 2.9.4
	OpenGL: Gallium 0.4 on NVA8 GL version 3.0 Mesa 11.0.2, nouveau
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU M 330 @ 2.13GHz
```

**Comment by mcccs** [comment]
What mods enabled?
Which server?

**Comment by WurstHackerEver** [comment]
I am having the same problem on every single server while using wurst but not on other hacked clients

**Comment by mcccs** [comment]
@bad2k00 Press Windows Button + R at the same time, then enter the following:
`%appdata%\.minecraft\wurst\modules.json`
Open it with your Notepad. Press Ctrl + F and search for `nuker`
Find these lines:
```json
  "Nuker": {
    "enabled": false
  },
  "NukerLegit": {
    "enabled": false
  },
```
If the `enabled` has a property of `true` change it with `false`.

**Comment by XxZaeKillerxX** [comment]
thanks!

**Comment by WurstHackerEver** [comment]
Thanks it worked! I will remember to never turn nuker on again xD.

**Comment by ZackTUC** [comment]
My problem is that when i join a game in a server it crash

**Comment by DuckerTracker** [comment]
@ZackTUC Same... I have the problem when I join to mineplex and be there like 5-10 seconds...

**Comment by haolang3** [comment]
i have the same prob but 1.8 with killauralegit i did what u said to do and it say 
d killauralegit not found
